# Generated by Django 5.2.1 on 2025-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250617_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('morning', 'Ráno (8:00 - 12:00)'), ('afternoon', 'Popoludnie (12:00 - 18:00)')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
