# Generated by Django 5.2.1 on 2025-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_time_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('morning', 'Ráno (8:00 - 12:00)'), ('afternoon', 'Odpoledne (12:00 - 18:00)')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='platba',
            field=models.CharField(choices=[('uhrazena', 'Uhrazená'), ('cekajici na platbu', 'Čekající na platbu')], default='cekajici na platbu', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nova', 'Nová'), ('zpracovani', 'Zpracování'), ('odeslano', 'Odesláno'), ('dorucena', 'Doručena')], default='nova', max_length=50),
        ),
    ]
