# Generated by Django 5.2.1 on 2025-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
    ]
