# Generated by Django 5.2.1 on 2025-05-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dummy_field',
        ),
    ]
