# Generated by Django 5.2.1 on 2025-05-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_dummy_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='parent',
            new_name='rodic',
        ),
    ]
