# Generated by Django 5.2.1 on 2025-05-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_parent_kategorie_rodic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategorie',
            old_name='rodic',
            new_name='parent',
        ),
    ]
